#!/bin/bash

LOG_DIRECTORY="${SCRIPT_DIRECTORY}/log"
CONFIG_DIRECTORY="${SCRIPT_DIRECTORY}/config"
SSH_DIRECTORY="${SCRIPT_DIRECTORY}/ssh"
SECURITY_DIRECTORY="${SCRIPT_DIRECTORY}/security"
TMP_DIRECTORY="${SCRIPT_DIRECTORY}/tmp"

CURRENT_DATE=`date +"%Y%m%d"`

LOG_FILENAME="${LOG_DIRECTORY}/deploy_${CURRENT_DATE}.log"


